//
//  S_LINK_DATA_STRING_HEADER.h
//
// 縺薙ｌ縺ｯ繝・・繝ｫ縺ｧ閾ｪ蜍募・蜉帙＆繧後ｋ繧ゅ・縺ｧ縺・
// 螟画焚蜷阪・縺ｿ螟画峩縺ｧ縺阪∪縺・
#if !defined(__S_LINK_DATA_STRING_HEADERﾌ__)
#define __S_LINK_DATA_STRING_HEADERﾌ__

enum eLINK_DATA_STRING_HEADER{
	eLINK_DATA_STRING_HEADER_START = 0,

	eLINK_DATA_STRING_HEADER_STRING_TEST_01 = eLINK_DATA_STRING_HEADER_START,
	eLINK_DATA_STRING_HEADER_STRING_TEST_02 ,
	eLINK_DATA_STRING_HEADER_STRING_TEST_03 ,

	eLINK_DATA_STRING_HEADER_NUM,
	eLINK_DATA_STRING_HEADER_MAX = eLINK_DATA_STRING_HEADER_NUM - 1,
};

#endif // !defined(__S_LINK_DATA_STRING_HEADERﾌ__)
