//
//  SampleHeader.h
//
// This file was generated by Tool.
// It is possibe to change only the enum name.
#if !defined(__SampleHeader__)
#define __SampleHeader__

enum eLINK_DATA_STRING_HEADER{
	eLINK_DATA_STRING_HEADER_START = 0,

	eLINK_DATA_STRING_HEADER_STRING_TEST_01 = eLINK_DATA_STRING_HEADER_START,
	eLINK_DATA_STRING_HEADER_STRING_TEST_02 ,
	eLINK_DATA_STRING_HEADER_STRING_TEST_03 ,

	eLINK_DATA_STRING_HEADER_NUM,
	eLINK_DATA_STRING_HEADER_MAX = eLINK_DATA_STRING_HEADER_NUM - 1,
};

#endif // !defined(__SampleHeader__)
