#include "Error.h"

// エラー定数.
const short CError::ERR_ARG_REQUIRED_PARAMETER_INPUT_FILE = 101;
const short CError::ERR_ARG_REQUIRED_PARAMETER_OUTPUT_FILE = 102;
const short CError::ERR_ARG_REQUIRED_PARAMETER_ENDIAN = 103;
const short CError::ERR_ARG_REQUIRED_PARAMETER_FILEVERSION = 104;
const short CError::ERR_ARG_ILLEGAL_PARAMETER_INPUT_FILE_VALUE = 201;
const short CError::ERR_ARG_ILLEGAL_PARAMETER_OUTPUT_FILE_VALUE = 202;
const short CError::ERR_ARG_ILLEGAL_PARAMETER_ENDIAN_VALUE = 203;
const short CError::ERR_ARG_ILLEGAL_PARAMETER_FILEVERSION_VALUE = 204;
const short CError::ERR_ARG_UNKNOWN_PARAMETER_ENDIAN_VALUE = 301;
const short CError::ERR_ARG_NOT_DIGIT_PARAMETER_FILEVERSION_VALUE = 401;
const short CError::ERR_INV_INPUT_FILE_NOT_OPEN = 501;
const short CError::ERR_INV_OUTPUT_FILE_NOT_OPEN = 502;
