#if !defined(__tool__Error__)
#define __tool__Error__
enum{
    ERR_ARG_REQUIRED_PARAMETER_INPUT_FILE = 101,
    ERR_ARG_REQUIRED_PARAMETER_OUTPUT_FILE = 102,
    ERR_ARG_REQUIRED_PARAMETER_ENDIAN = 103,
    ERR_ARG_REQUIRED_PARAMETER_FILEVERSION = 104,
    ERR_ARG_ILLEGAL_PARAMETER_INPUT_FILE_VALUE = 201,
    ERR_ARG_ILLEGAL_PARAMETER_OUTPUT_FILE_VALUE = 202,
    ERR_ARG_ILLEGAL_PARAMETER_ENDIAN_VALUE = 203,
    ERR_ARG_ILLEGAL_PARAMETER_FILEVERSION_VALUE = 204,
    ERR_ARG_UNKNOWN_PARAMETER_ENDIAN_VALUE = 301,
    ERR_ARG_NOT_DIGIT_PARAMETER_FILEVERSION_VALUE = 401,
    ERR_INV_INPUT_FILE_NOT_OPEN = 501,
    ERR_INV_OUTPUT_FILE_NOT_OPEN = 502,
    ERR_INV_WORK_FILE_NOT_OPEN = 503,
    
};
#endif // !defined(__tool__Error__)
